version: '2.2'
services:
  metronome:
    build: .
    ports:
      - 2003:2003
    volumes:
      - ./metronome/local.js:/usr/share/metronome/html/local.js:ro
      - /usr/share/metronome/stats:/usr/share/metronome/stats
    restart: always
  nginx: 
    image: nginx:latest
    links: 
      - "metronome"
    volumes_from:
      - metronome:ro
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    restart: always